#
#
#
SUBDIRS =

INCDIR   = ../../include
LIBDIR   = ../../lib

LIBNAME = n2pw

OBJ_OPTIMIZE = hdbm.o rtdb_seq.o rtdb.o control.o

HPPINCLUDES = control.hpp rtdb.hpp


include ../../config/makefile.h

