#
#
#

SUBDIRS =
INCDIR  = ../../include
LIBDIR  = ../../lib

LIBNAME = n2pw

OBJ_OPTIMIZE = lattice.o Balance.o PGrid.o Strfac.o

HPPINCLUDES = lattice.hpp Balance.hpp PGrid.hpp Strfac.hpp


include ../../config/makefile.h

