#
#
#
#
#
#
SUBDIRS =

INCDIR   = ../../include
LIBDIR   = ../../lib

LIBNAME = n2pw

OBJ_OPTIMIZE = hilbert.o Mapping1.o Mapping3.o Pneb.o d3db.o d1db.o

HPPINCLUDES = d3db.hpp d1db.hpp Pneb.hpp Mapping3.hpp Mapping1.hpp



include ../../config/makefile.h

