#
#
#
SUBDIRS =

INCDIR   = ../../include
LIBDIR   = ../../lib

LIBNAME = fftpack


#SOURCES = cfftb.f cfftb1.f cfftf.f cfftf1.f cffti.f cffti1.f \
#	cosqb.f cosqb1.f cosqf.f cosqf1.f cosqi.f cost.f \
#	costi.f dcfftb.f dcfftf.f dcffti.f dcftb1.f dcftf1.f \
#	dcfti1.f dpssb.f dpssb2.f dpssb3.f dpssb4.f dpssb5.f \
#	dpssf.f dpssf2.f dpssf3.f dpssf4.f dpssf5.f dradb2.f \
#	dradb3.f dradb4.f dradb5.f dradbg.f dradf2.f dradf3.f \
#	dradf4.f dradf5.f dradfg.f drfftb.f drfftf.f drffti.f \
#	drftb1.f drftf1.f drfti1.f passb.f passb2.f passb3.f \
#	passb4.f passb5.f passf.f passf2.f passf3.f passf4.f \
#	passf5.f radb2.f radb3.f radb4.f radb5.f radbg.f radf2.f \
#	radf3.f radf4.f radf5.f radfg.f rfftb1.f rfftb.f rfftf.f \
#	rfftf1.f rffti.f rffti1.f sinqb.f sinqf.f sinqi.f \
#	sint.f sint1.f sinti.f

OBJ_OPTIMIZE = cfftb.o cfftb1.o cfftf.o cfftf1.o cffti.o cffti1.o \
	cosqb.o cosqb1.o cosqf.o cosqf1.o cosqi.o cost.o \
	costi.o dcfftb.o dcfftf.o dcffti.o dcftb1.o dcftf1.o \
	dcfti1.o dpssb.o dpssb2.o dpssb3.o dpssb4.o dpssb5.o \
	dpssf.o dpssf2.o dpssf3.o dpssf4.o dpssf5.o dradb2.o \
	dradb3.o dradb4.o dradb5.o dradbg.o dradf2.o dradf3.o \
	dradf4.o dradf5.o dradfg.o drfftb.o drfftf.o drffti.o \
	drftb1.o drftf1.o drfti1.o passb.o passb2.o passb3.o \
	passb4.o passb5.o passf.o passf2.o passf3.o passf4.o \
	passf5.o radb2.o radb3.o radb4.o radb5.o radbg.o radf2.o \
	radf3.o radf4.o radf5.o radfg.o rfftb.o rfftb1.o rfftf.o \
	rfftf1.o rffti.o rffti1.o sinqb.o sinqf.o sinqi.o \
	sint.o sint1.o sinti.o

HPPINCLUDES = fft.h


include ../../config/makefile.h
